export const DISPLAY_ERROR_POPUP = 'POPUPS::DISPLAY_ERROR_POPUP';
export const DISPLAY_INFO_POPUP = 'POPUPS::DISPLAY_INFO_POPUP';
export const DISPLAY_CONFIRM_POPUP = 'POPUPS::DISPLAY_CONFIRM_POPUP';
export const DISPLAY_CUSTOM_POPUP = 'POPUPS::DISPLAY_CUSTOM_POPUP';
export const CLOSE_POPUP = 'POPUPS::CLOSE_POPUP';
