export const USERNAME_INPUT_VALUE = 'LOGIN::USERNAME_INPUT_VALUE';
export const PASSWORD_INPUT_VALUE = 'LOGIN::PASSWORD_INPUT_VALUE';
export const LOGIN_SUCCESS = 'LOGIN::LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN::LOGIN_FAILURE';
export const EMPTY_FIELDS_ERROR = 'LOGIN::EMPTY_FIELDS_ERROR';
export const REMOVE_TOKEN = 'LOGIN::REMOVE_TOKEN';
export const LOGIN_START = 'LOGIN::LOGIN_START';
