export const FETCH_START = 'USER_MODELS::FETCH_START';
export const FETCH_ERROR = 'USER_MODELS::FETCH_ERROR';
export const FETCH_SUCCESS = 'USER_MODELS::FETCH_SUCCESS';
export const CHANGE_SEARCH_INPUT = 'USER_MODELS::CHANGE_SEARCH_INPUT';
