export const FORM_USER_TYPE_INPUT_VALUE = 'CREATE_USERS::FORM_USER_TYPE_INPUT_VALUE';
export const FORM_DESCRIPTION_INPUT_VALUE = 'CREATE_USERS::FORM_DESCRIPTION_INPUT_VALUE';
export const FORM_USERNAME_INPUT_VALUE = 'CREATE_USERS::FORM_USERNAME_INPUT_VALUE';
export const FORM_PASSWORD_INPUT_VALUE = 'CREATE_USERS::FORM_PASSWORD_INPUT_VALUE';
export const FORM_PASSWORD_REPEAT_INPUT_VALUE = 'CREATE_USERS::FORM_PASSWORD_REPEAT_INPUT_VALUE';
export const PASSWORD_LENGTH_ERROR = 'CREATE_USERS::PASSWORD_LENGTH_ERROR';
export const PASSWORD_EQUAL_ERROR = 'CREATE_USERS::PASSWORD_EQUAL_ERROR';
export const EMPTY_FIELDS_ERROR = 'CREATE_USERS::EMPTY_FIELDS_ERROR';
export const CREATE_START = 'CREATE_USERS::CREATE_USER';
export const CREATE_SUCCESS = 'ADMIN_USERS::CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_USERS::CREATE_FAILURE';
export const SET_USERS = 'CREATE_USERS::SET_USERS';
export const ONCLOSE_ACTION = 'CREATE_USERS::ONCLOSE_ACTION';

export const USER_FOR_EDITING = 'CREATE_USERS::USER_FOR_EDITING';
export const EDIT_SUCCESS = 'ADMIN_USERS::EDIT_SUCCESS';
export const SHOW_EDIT = 'CREATE_USERS::SHOW_EDIT';
