export const FETCH_START = 'USER_DASHBOARDS::FETCH_START';
export const FETCH_ERROR = 'USER_DASHBOARDS::FETCH_ERROR';
export const FETCH_SUCCESS = 'USER_DASHBOARDS::FETCH_SUCCESS';
export const CHANGE_SEARCH_INPUT = 'USER_DASHBOARDS::CHANGE_SEARCH_INPUT';
export const NEW_DASHBOARD = 'USER_DASHBOARDS::NEW_DASHBOARD';
export const SET_DASHBOARD_FOR_DELETE = 'USER_DASHBOARDS::SET_DASHBOARD_FOR_DELETE';
export const DELETE_DASHBOARD_SUCCESS = 'USER_DASHBOARDS::DELETE_DASHBOARD_SUCCESS';
